### ISSUE TITLE
'FileCitation' object has no attribute 'quote'

### ISSUE THREAD

**Issue by esseti** [openai/openai-python#1498]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

After the last update i've tried to use my code that does what explained also here. https://platform.openai.com/docs/assistants/how-it-works/managing-threads-and-messages

Now when accessing the .quote i receive the error as above

'FileCitation' object has no attribute 'quote'.

can it be that they changed the api? (i don't find annotations description in the docs)

### To Reproduce

1. Create an assistant with files associated
2. ask a question that has filecitation
3. check to get the file_citation.quote

### OS

macOs

### Python version

3.12

### Library version

1.30.5

**Comment by dgellow** [comment]
Hi @esseti,

If you are getting `FileCitation` has no attribute 'quote'` that does sound like an API issue, not a problem with the SDK per-se.

I would recommend to contact OpenAI directly. The SDK is generated based on OpenAI spec file, and `quote` is indeed an optional field of `file_citation`:

https://github.com/openai/openai-openapi/blob/0df12d7b3ac997517fda38842f41d99a8e7f4e6a/openapi.yaml#L11750-L11758

```
                file_citation:
                    type: object
                    properties:
                        file_id:
                            description: The ID of the specific File the citation is from.
                            type: string
                        quote:
                            description: The specific quote in the file.
                            type: string
```
